---
title: "lit_review"
author: "Alina Levine"
date: "November 30, 2019"
output: html_document
---


In the United States racial disparities in healthcare has been a widely studied area. Racial disparities and healthcare studies have covered many domains including racial differences access to healthcare, quality of healthcare, and representation as healthcare professionals. (https://annals.org/aim/fullarticle/717703/racial-ethnic-disparities-health-care-position-paper-american-college-physicians) 
    Socioeconomic factors are one area that have caused minority groups to be disadvantaged in healthcare, specifically in access to healthcare. Lower health insurance coverage amongst minorities is one reason health outcomes are thought to be worse for minority groups. People without health insurance often have to delay or skip needed medical visits due to cost, and thus, are not able to take care of their medical needs.https://www.kff.org/report-section/the-uninsured-and-the-aca-a-primer-key-facts-about-health-insurance-and-the-uninsured-amidst-changes-to-the-affordable-care-act-how-does-lack-of-insurance-affect-access-to-care/  In 2017, Hispanics had about three times the rate of not being insured compared to whites (25 percent versus 8 percent) and blacks had almost double the rate of non-insurance compared to whites (13.8 percent versus percent) https://www.commonwealthfund.org/publications/issue-briefs/2019/aug/did-ACA-reduce-racial-ethnic-disparities-coverage . Note that these disparities are three years after the implementation of the affordable care act, which actually reduced the racial disparities in health insurance coverage. 
    Even amongst the insured there are racial disparities for type of insurance, public versus private.In the 2007 census, it was estimated that 50 percent of people enrolled in medicaid or medicare were part of a minority group. Medicaid and medicare may not always be reliable sources of health insurance due to these programs' sensitivities to the state of the economy.https://www.acponline.org/acp_policy/policies/racial_ethnic_disparities_2010.pdf, in terms of how much the government will spend on these programs.There are further disparities even within public insurance users. Black people who are eligible for dual coverage (medicare and medicaid) are less likely than white people to get medicare coverage.
    There are additional reasons why health outcomes for minority groups are worse than those for whites. Discrimination and implicit bias hurt the quality of the healthcare to which minority groups do get access, which in turn can keep minority groups from getting access to the healthcare they actually need. Physicians may act on stereotypes. For example, black patients are less likely to go for ________ than white patients.  https://www.healthaffairs.org/doi/full/10.1377/hlthaff.24.2.445 Additionally, people in minority groups may live in neighborhoods where good medical care is not available, thereby keeping minorities from getting the needed healthcare.
    https://www.acponline.org/acp_policy/policies/racial_ethnic_disparities_2010.pdf. 
    We wanted to specifically look at the relationship between race and healthcare access in New York City in 2018 using the Community Health Survey. We hypothesized that racial minorities would have lower access to care than the white population. By access to care we were interested in people's ability to get healthcare when they believed it was necessary and whether they were under the continuous care of 1 or 2 primary care doctors. Additinally, we wanted to see if health insurance fully explained the role of race in healthcare access or if race was associated with healthcare access even when we accounted for type of health insurance.
    
    Limitations
    
    Our study only looks at the surface of health care access and race. It is one thing to get access to a doctor but another to get access to a doctor that gives the same quality care regardless of race. With a more comprehensive survey we could look at the association between race and access to quality health care with and without controlling for economic factors such as health insurance and income. For example, it has been shown that black people are less likley than white people to be referred to _____ for _____. If a survey in NYC had that question, we could compare between races. We can also look at patient satisfaction with their healthcare. 
    In addition to this limitation, our study is limited by the population that was surveyed. ONly people living in non group residences were surveyed. Therefore, this excludes many students and older adults living in assisted livings, so these results cannot be generalized to the general NYC adult population. 